### PR TITLE
use the openshift admin role instead of edit and make sure we always have the latest che server image

### PR DESCRIPTION
**Pull request by rawlingsj**

### CODE REVIEW

**Comment by rawlingsj** [comment]
@l0rd are you happy for the commits above for the Che yaml?

**Comment by l0rd** [comment]
@rawlingsj 👍 

I've added some more updates: https://github.com/fabric8io/fabric8-online/pull/84

**Comment by rawlingsj** [comment]
great @l0rd!

**Comment by rawlingsj** [comment]
[merge]

**Pull request merged**
