### PR TITLE
Changing image to rhche/che-server:nightly

### PR DESCRIPTION
**Pull request by ibuziuk**

### CODE REVIEW

**Comment by rawlingsj** [comment]
good call - thanks!

**Comment by rawlingsj** [comment]
@ibuziuk want me to kick off a fabric8-online release?

**Comment by ibuziuk** [comment]
@rawlingsj would be great!

**Comment by rawlingsj** [comment]
Done - should be in maven central in ~15 mins.

BTW you probably already know but you can generate the yaml and deploy it using this project.

i.e..
```
oc login (to minishift say)
cd apps/che
mvn fabric8:deploy
gofabric8 volumes
```

**Comment by ibuziuk** [comment]
@rawlingsj cool, I did not know this. Thanks for the pointer!

**Pull request merged**
