### PR TITLE
che-262: Adding env vars for managing keycloak endpoints (oso / github)

### PR DESCRIPTION
**Pull request by ibuziuk**
Signed-off-by: Ilya Buziuk <ibuziuk@redhat.com>

### CODE REVIEW

**Comment by ibuziuk** [comment]
@l0rd could you please take a look ?

**Comment by l0rd** [comment]
LGTM

**Comment by ibuziuk** [comment]
@rawlingsj @l0rd could we merge this one ?

**Comment by l0rd** [comment]
[merge]

**Pull request merged**
